name: benchmarks
on: [pull_request, workflow_dispatch]

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

env:
  FORCE_COLOR: "1"
  PY_COLORS: "1"

jobs:
  bench:
    name: run benchmarks
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - uses: actions/setup-python@v5
        with:
            python-version: "3.12"

      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: astral-sh/setup-uv@v3
        with:
          enable-cache: true
          cache-dependency-glob: pyproject.toml

      - run: uv pip install '.[dev]' --system
      - run: uv pip install 'dvc-objects @ git+https://github.com/iterative/dvc-objects.git@no-copy-owner-info' --system
      - run: curl -O https://image-net.org/data/bboxes_annotations.tar.gz
      - run: tar zxvf bboxes_annotations.tar.gz
      - run: rm bboxes_annotations.tar.gz
      - run: |
          for file in ./*.tar.gz; do
            tar zxvf $file
          done
        shell: bash
      - run: time dvc add Annotation/ --cprofile-dump add.prof
        shell: bash
      - run: cat ./*.dvc
        shell: bash
      - run: time dvc add Annotation/ --cprofile-dump noop.prof
        shell: bash
      - uses: actions/upload-artifact@v4
        with:
          name: profiling-${{ matrix.os }}
          path: '*.prof'
